import { NextAuthProvider } from "@/components/NextAuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Headers/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "With Sports",
  description: "Generated by create next app",
};

// interface Styles {
//   display: string;
//   flexDirection?: string;
//   justifyContent: string;
//   height?: string;
//   alignItems?: string;
// }

// // Footer 하단 고정
// const contentWrapper: Styles = {
//   display: "flex",
// 	justifyContent: "center",
// 	alignItems: "center",
// }

// const wrapper : Styles = {
//   display: "flex",
// 	flexDirection: "column",
// 	justifyContent: "space-between",
// 	height: "100vh"
// }

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          {/* <div className='wrapper' style={wrapper}> */}
          <Header />
          {/* <div className='contentWrapper' style={contentWrapper}> */}
          {children}
          {/* </div> */}
          <Footer />
          {/* </div> */}
        </NextAuthProvider>
      </body>
    </html>
  );
}
